# Generated by Django 2.1.3 on 2018-11-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home01', '0004_auto_20181105_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='home01.Author'),
        ),
    ]
