# Generated by Django 2.1.3 on 2018-11-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home01', '0006_auto_20181106_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='aid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='publish',
            old_name='pid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home01.Author', to_field='aid'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home01.Publish', to_field='pid'),
        ),
    ]
